-- Atualiza imagens dos produtos (PremieRpet 2026) — reexecutável
BEGIN;
UPDATE products SET image = '/assets/products/catalog/page-11-img-04.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Grande - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-09-img-05.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Médio - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-09-img-05.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Médio - Sabor Frango e Arroz' AND COALESCE(weight,'') = '20kg';
UPDATE products SET image = '/assets/products/catalog/page-09-img-05.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Médio - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-10-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Médio - Sabor Salmão e Arroz; Peru e' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-10-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Médio - Sabor Salmão e Arroz; Peru e' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-15-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Banana, Aveia e Mel' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-14-img-04.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Banana,Aveia' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-12-img-03.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Carne, Espinafre e Cenoura' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-15-img-05.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Carne,Cenoura e' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-09-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Frango e Arroz; Carne e' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-09-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Frango e Arroz; Carne e' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-09-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Frango e Arroz; Carne e' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-09-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Frango e Arroz; Carne e' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-12-img-03.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Frango, Espinafre e Cenoura' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-15-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Maçã e Aveia' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-15-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Original' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-15-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Original' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-15-img-04.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Porte Pequeno - Sabor Salmão e Quinoa' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-11-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-07-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Sabor Frango e Carne' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-13-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Sabor Frango, Batata-Doce e Cenoura' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-13-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Adultos - Sabor Frango, Espinafre e Cenoura' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-08-img-04.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Médio - Sabor Carne e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-04.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Médio - Sabor Carne e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-04.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Médio - Sabor Carne e Arroz' AND COALESCE(weight,'') = '20kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-04.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Médio - Sabor Carne e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-03.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Médio - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-03.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Médio - Sabor Frango e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-03.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Médio - Sabor Frango e Arroz' AND COALESCE(weight,'') = '20kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-03.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Médio - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Pequeno - Sabor Carne e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Pequeno - Sabor Carne e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Pequeno - Sabor Carne e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-08-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-07-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Pequeno - Sabor Frango e Carne' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-07-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Porte Pequeno - Sabor Frango e Carne' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-12-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Sabor Frango, Espinafre e Cenoura' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-14-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Sabor Maçã e Aveia' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-14-img-01.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Sabor Original' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-14-img-02.webp', updated_at = NOW() WHERE name = 'Golden - Filhotes - Sabor Salmão e Quinoa' AND COALESCE(weight,'') = '350g';
UPDATE products SET image = '/assets/products/catalog/page-11-img-05.webp', updated_at = NOW() WHERE name = 'Golden - Light - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-10-img-04.webp', updated_at = NOW() WHERE name = 'Golden - Senior - Porte Pequeno - Sabor Frango e Arroz; Carne e' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-10-img-03.webp', updated_at = NOW() WHERE name = 'Golden - Senior - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-18-img-02.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Adultos - Sabor Frango' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-18-img-02.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Adultos - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-18-img-02.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Adultos - Sabor Frango' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-19-img-01.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Castrados - Sabor Frango' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-19-img-01.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Castrados - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-19-img-01.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Castrados - Sabor Frango' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-17-img-02.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Castrados - Sabor Frango e Carne' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-17-img-02.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Castrados - Sabor Frango e Carne' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-17-img-02.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Castrados - Sabor Frango e Carne' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-18-img-01.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Filhotes - Sabor Frango' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-18-img-01.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Filhotes - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-18-img-01.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Filhotes - Sabor Frango' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-19-img-03.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Senior - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-19-img-03.webp', updated_at = NOW() WHERE name = 'Golden Gatos - Senior - Sabor Frango' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-20-img-02.webp', updated_at = NOW() WHERE name = 'Golden Gourmet Gatos - Adultos - Sabor Atum e Abóbora' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-20-img-05.webp', updated_at = NOW() WHERE name = 'Golden Gourmet Gatos - Adultos - Sabor Carne e Abóbora' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-20-img-03.webp', updated_at = NOW() WHERE name = 'Golden Gourmet Gatos - Adultos - Sabor Frango e Abóbora' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-20-img-01.webp', updated_at = NOW() WHERE name = 'Golden Gourmet Gatos - Filhotes - Sabor Frango e Arroz' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-23-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Adultos - Porte Pequeno - Sabor Frango' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-23-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Adultos - Porte Pequeno - Sabor Frango' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-22-img-04.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Adultos - Porte Pequeno - Sabor Frango com Abóbora e Alecrim' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-22-img-03.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Adultos - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-23-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Adultos - Sabor Frango' AND COALESCE(weight,'') = '12kg';
UPDATE products SET image = '/assets/products/catalog/page-23-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Adultos - Sabor Frango' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-23-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Adultos - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-22-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-22-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-22-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-22-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-24-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Senior - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-24-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Senior - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-24-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Cães - Senior - Sabor Frango e Arroz' AND COALESCE(weight,'') = '12kg';
UPDATE products SET image = '/assets/products/catalog/page-25-img-02.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Gatos - Adultos - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-25-img-02.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Gatos - Adultos - Sabor Frango e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-25-img-02.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Gatos - Adultos - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-25-img-03.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Gatos - Castrados - Sabor Frango com' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-25-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Gatos - Filhotes - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-25-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Gatos - Filhotes - Sabor Frango e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-25-img-01.webp', updated_at = NOW() WHERE name = 'Golden Seleção Natural Gatos - Filhotes - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-03.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, Mandioca' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-03.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, Mandioca' AND COALESCE(weight,'') = '12kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-03.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, Mandioca' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-03.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, Mandioca' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-03.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, Mandioca' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, abóbora, brócolis, quinoa e blueberry' AND COALESCE(weight,'') = '12kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, abóbora, brócolis, quinoa e' AND COALESCE(weight,'') = '12kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, mandioquinha' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, mandioquinha' AND COALESCE(weight,'') = '12kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, mandioquinha' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, mandioquinha' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Adultos - Sabor Frango, mandioquinha' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Filhotes - Sabor Frango, mandioca' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Filhotes - Sabor Frango, mandioca' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Filhotes - Sabor Frango, mandioca' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-48-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Filhotes - Sabor Frango, mandioca' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-05.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Grain Free - Porte Pequeno - Sabor Frango, batata-doce, ervilha, blueberry e' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-49-img-05.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Grain Free - Porte Pequeno - Sabor Frango, batata-doce, ervilha, blueberry e' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-50-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Senior - Sabor Frango, mandioca' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-51-img-02.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Castrados - Sabor Frango, abóbora, brócolis' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-51-img-02.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Castrados - Sabor Frango, mandioca' AND COALESCE(weight,'') = '7.5kg';
UPDATE products SET image = '/assets/products/catalog/page-51-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Cães - Filhotes - Sabor Frango, abóbora, brócolis' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-52-img-03.webp', updated_at = NOW() WHERE name = 'Nattu Gatos - Adultos - Porte Pequeno - Sabor Frango, batata doce' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-53-img-02.webp', updated_at = NOW() WHERE name = 'Nattu Gatos - Castrados - Sabor Frango, Abóbora, Brócolis e' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-52-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Gatos - Filhotes - Sabor Frango, abóbora, brócolis e' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-52-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Gatos - Filhotes - Sabor Frango, abóbora, brócolis e A partir de 12 meses' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-52-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Gatos - Filhotes - Sabor quinoa' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-54-img-01.webp', updated_at = NOW() WHERE name = 'Nattu Úmidos - Produto - Sabor Frango, batata-doce, brócolis, cenoura e cranberry' AND COALESCE(weight,'') = '60g';
UPDATE products SET image = '/assets/products/catalog/page-31-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Ambientes Internos - Adultos - Porte Pequeno - Sabor Frango e Salmão' AND COALESCE(weight,'') = '12kg';
UPDATE products SET image = '/assets/products/catalog/page-31-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Ambientes Internos - Adultos - Porte Pequeno - Sabor Frango e Salmão' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-31-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Ambientes Internos - Adultos - Porte Pequeno - Sabor Frango e Salmão' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-31-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Ambientes Internos - Adultos - Porte Pequeno - Sabor Frango e Salmão' AND COALESCE(weight,'') = '7.5kg';
UPDATE products SET image = '/assets/products/catalog/page-32-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Ambientes Internos - Castrados - Porte Pequeno - Sabor Salmão' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-31-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Ambientes Internos - Filhotes - Porte Pequeno - Sabor Frango e Salmão' AND COALESCE(weight,'') = '12kg';
UPDATE products SET image = '/assets/products/catalog/page-32-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Ambientes Internos - Sênior - Sabor Frango e Salmão' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-42-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Adultos - Porte Pequeno - Sabor Frango' AND COALESCE(weight,'') = '250g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Adultos - Porte Pequeno - Sabor Original' AND COALESCE(weight,'') = '250g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Adultos - Porte Pequeno - Sabor Original' AND COALESCE(weight,'') = '250g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Filhotes - Porte Pequeno - Sabor Original' AND COALESCE(weight,'') = '250g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Filhotes - Porte Pequeno - Sabor Coco e Aveia' AND COALESCE(weight,'') = '250g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Filhotes - Porte Pequeno - Sabor Coco e aveia' AND COALESCE(weight,'') = '250g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Filhotes - Porte Pequeno - Sabor Frutas Vermelhas e Aveia' AND COALESCE(weight,'') = '250g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Filhotes - Porte Pequeno - Sabor Frutas Vermelhas e Aveia' AND COALESCE(weight,'') = '50g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Filhotes - Porte Pequeno - Sabor Frutas vermelhas e aveia' AND COALESCE(weight,'') = '50g';
UPDATE products SET image = '/assets/products/catalog/page-41-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Cookie - Adultos - Porte Pequeno - Sabor Original' AND COALESCE(weight,'') = '40g';
UPDATE products SET image = '/assets/products/catalog/page-28-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Formula Cães - Adultos - Porte Grande - Sabor Frango e Mandioca Sabores: Frango e Mandioca' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-27-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Formula Cães - Adultos - Porte Médio - Sabor Frango e Mandioca' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-27-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Formula Cães - Adultos - Porte Pequeno - Sabor Carne e batata-doce; Frango e' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-27-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Formula Cães - Adultos - Porte Pequeno - Sabor Frango e mandioca' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-28-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Formula Cães - Light - Porte Grande - Sabor Frango e Mandioca' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-28-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Formula Cães - Light - Porte Grande - Sabor Frango e Mandioca; Cordeiro' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-28-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Formula Cães - Light - Porte Médio - Sabor Frango e Mandioca' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-29-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Formula Gatos - Adultos - Sabor Frango' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-29-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Formula Gatos - Adultos - Sabor Frango' AND COALESCE(weight,'') = '7.5kg';
UPDATE products SET image = '/assets/products/catalog/page-29-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Formula Gatos - Castrados - Sabor Frango' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-29-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Formula Gatos - Castrados - Sabor Frango' AND COALESCE(weight,'') = '7.5kg';
UPDATE products SET image = '/assets/products/catalog/page-30-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Formula Úmidos - Castrados - Sabor Atum, brócolis e cenoura' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-30-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Formula Úmidos - Castrados - Sabor Frango, brócolis e cenoura' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-30-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Formula Úmidos - Úmidos - Sabor Carne, brócolis e cenoura' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-30-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Formula Úmidos - Úmidos - Sabor Frango, brócolis e cenoura' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-33-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Gatos - Adultos - Pelos Longos - Sabor Frango' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-34-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Gatos - Castrados - Sabor Frango' AND COALESCE(weight,'') = '500g';
UPDATE products SET image = '/assets/products/catalog/page-33-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Gatos - Filhotes - Pelos Longos - Sabor Frango' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-33-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Gatos - Filhotes - Pelos Longos - Sabor Frango' AND COALESCE(weight,'') = '500g';
UPDATE products SET image = '/assets/products/catalog/page-33-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Gatos - Filhotes - Pelos Longos - Sabor Frango' AND COALESCE(weight,'') = '7.5kg';
UPDATE products SET image = '/assets/products/catalog/page-34-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Gatos - Light - Sabor Salmão' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-34-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Gatos - Light - Sabor Salmão' AND COALESCE(weight,'') = '7.5kg';
UPDATE products SET image = '/assets/products/catalog/page-39-img-05.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Adultos - Porte Médio - Sabor Peito de Frango, Batata Doce e Brócolis' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-39-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Adultos - Porte Pequeno - Sabor Carne, Batata Doce e Brócolis' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-39-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Adultos - Porte Pequeno - Sabor Salmão' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-39-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Filhotes - Porte Pequeno - Sabor Peito de Frango' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-39-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Filhotes - Porte Pequeno - Sabor Peito de Frango, Batata Doce e' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-40-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Adultos - Sabor Carne' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-40-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Adultos - Sabor Peito de Frango' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-40-img-04.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Castrados - Sabor Atum' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-40-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Gourmet - Castrados - Sabor Peito de Frango' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-46-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Orgânico - Adultos - Porte Pequeno - Sabor Frango, chia & quinoa orgânicos' AND COALESCE(weight,'') = '85g';
UPDATE products SET image = '/assets/products/catalog/page-46-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Orgânico - Adultos - Sabor Frango, chia & quinoa orgânicos' AND COALESCE(weight,'') = '70g';
UPDATE products SET image = '/assets/products/catalog/page-37-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Raças Específicas - Adultos - Porte Médio - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-35-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Raças Específicas - Adultos - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-36-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Raças Específicas - Adultos - Sabor Peru e Arroz' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-36-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Raças Específicas - Adultos - Sabor Peru e Arroz' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-36-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Raças Específicas - Adultos - Sabor Peru e Arroz' AND COALESCE(weight,'') = '7.5kg';
UPDATE products SET image = '/assets/products/catalog/page-35-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Raças Específicas - Filhotes - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-44-img-03.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Porte Médio - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-44-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Porte Pequeno - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-44-img-01.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Porte Pequeno - Sabor Frango' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-43-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Sabor Frango' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-43-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Sabor Frango' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-43-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Sabor Frango' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-43-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Sabor Frango e Batata Doce' AND COALESCE(weight,'') = '1kg';
UPDATE products SET image = '/assets/products/catalog/page-44-img-05.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Sabor Frango e batata doce' AND COALESCE(weight,'') = '2.5kg';
UPDATE products SET image = '/assets/products/catalog/page-43-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Adultos - Sabor Frango' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-45-img-02.webp', updated_at = NOW() WHERE name = 'PremieR Seleção Natural - Castrados - Sabor Frango' AND COALESCE(weight,'') = '1.5kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-02.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Adultos - Porte Pequeno - Sabor Carne e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-02.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Adultos - Porte Pequeno - Sabor Carne e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-02.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Adultos - Porte Pequeno - Sabor Carne e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Adultos - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Adultos - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Adultos - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-02.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Adultos - Sabor Carne e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Adultos - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-04-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-04-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-04-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-04-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
UPDATE products SET image = '/assets/products/catalog/page-04-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Filhotes - Porte Pequeno - Sabor Frango e Arroz' AND COALESCE(weight,'') = '3kg';
UPDATE products SET image = '/assets/products/catalog/page-04-img-01.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Filhotes - Sabor Frango e Arroz' AND COALESCE(weight,'') = '15kg';
UPDATE products SET image = '/assets/products/catalog/page-05-img-05.webp', updated_at = NOW() WHERE name = 'Vitta Natural - Castrados - Sabor Frango e Arroz' AND COALESCE(weight,'') = '10.1kg';
COMMIT;
